PL_TO_EN = {
    "sprzedaż": "sales",
    "sprzedaz": "sales",
    "sprzedaży": "sales",
    "sprzedazy": "sales",
    "stan": "stock",
    "stanu": "stock",
    "zapas": "stock",
    "zapasu": "stock",
    "magazyn": "stock",
    "magazynu": "stock",
    "prognoza": "forecast",
    "prognozy": "forecast",
    "prognozę": "forecast",
    "prognoze": "forecast",
    "model": "model",
    "modelu": "model",
    "modele": "models",
    "modeli": "models",
    "kolor": "color",
    "koloru": "color",
    "kolory": "colors",
    "kolorów": "colors",
    "kolorow": "colors",
    "rozmiar": "size",
    "rozmiaru": "size",
    "rozmiary": "sizes",
    "rozmiarów": "sizes",
    "rozmiarow": "sizes",
    "ostatnie": "last",
    "ostatnich": "last",
    "rok": "year",
    "roku": "year",
    "lat": "years",
    "lata": "years",
    "miesiąc": "month",
    "miesiac": "month",
    "miesiąca": "month",
    "miesiaca": "month",
    "miesiące": "months",
    "miesiace": "months",
    "miesięcy": "months",
    "miesiecy": "months",
    "tydzień": "week",
    "tydzien": "week",
    "tygodnia": "week",
    "tygodnie": "weeks",
    "tygodni": "weeks",
    "dzień": "day",
    "dzien": "day",
    "dnia": "day",
    "dni": "days",
    "top": "top",
    "najlepsze": "top",
    "najlepszych": "top",
    "bestsellery": "bestsellers",
    "bestsellerów": "bestsellers",
    "bestsellerow": "bestsellers",
    "poniżej": "below",
    "ponizej": "below",
    "powyżej": "above",
    "powyzej": "above",
    "mniej": "less",
    "więcej": "more",
    "wiecej": "more",
    "równe": "equal",
    "rowne": "equal",
    "sezonowy": "seasonal",
    "sezonowe": "seasonal",
    "sezonowych": "seasonal",
    "podstawowy": "basic",
    "podstawowe": "basic",
    "podstawowych": "basic",
    "regularny": "regular",
    "regularne": "regular",
    "regularnych": "regular",
    "nowy": "new",
    "nowe": "new",
    "nowych": "new",
    "wszystkie": "all",
    "wszystkich": "all",
    "suma": "sum",
    "sumy": "sum",
    "średnia": "average",
    "średnią": "average",
    "srednia": "average",
    "ilość": "quantity",
    "ilosc": "quantity",
    "ilości": "quantity",
    "ilosci": "quantity",
    "sztuk": "pieces",
    "sztuki": "pieces",
    "wartość": "value",
    "wartosc": "value",
    "wartości": "value",
    "wartosci": "value",
    "cena": "price",
    "ceny": "price",
    "szwalnia": "facility",
    "szwalni": "facility",
    "fabryka": "facility",
    "fabryki": "facility",
    "przez": "by",
    "według": "by",
    "wedlug": "by",
    "wg": "by",
    "dla": "for",
    "z": "from",
    "do": "to",
    "od": "from",
    "i": "and",
    "lub": "or",
    "albo": "or",
    "nie": "not",
    "bez": "without",
    "tylko": "only",
    "gdzie": "where",
    "który": "which",
    "ktory": "which",
    "które": "which",
    "ktore": "which",
    "jak": "how",
    "ile": "how many",
    "jaki": "what",
    "jaka": "what",
    "jakie": "what",
    "pokaż": "show",
    "pokaz": "show",
    "wyświetl": "show",
    "wyswietl": "show",
    "znajdź": "find",
    "znajdz": "find",
    "szukaj": "search",
    "lista": "list",
    "listy": "list",
    "raport": "report",
    "raportu": "report",
    "typ": "type",
    "typu": "type",
    "typy": "types",
    "typów": "types",
    "typow": "types",
    "kategoria": "category",
    "kategorii": "category",
    "zerowy": "zero",
    "zerowym": "zero",
    "zerowe": "zero",
    "brak": "missing",
    "braku": "missing",
    "brakujące": "missing",
    "brakujace": "missing",
}

ENTITY_KEYWORDS = {
    "sales": ["sales", "sold", "selling", "revenue"],
    "stock": ["stock", "inventory", "available", "warehouse"],
    "forecast": ["forecast", "prediction", "predicted", "expected"],
}

AGGREGATION_KEYWORDS = {
    "month": ["month", "monthly", "months"],
    "year": ["year", "yearly", "years", "annual"],
    "model": ["model", "models"],
    "color": ["color", "colors"],
    "size": ["size", "sizes"],
    "week": ["week", "weekly", "weeks"],
    "day": ["day", "daily", "days"],
}

FILTER_KEYWORDS = {
    "below_rop": ["below rop", "under rop", "reorder", "need reorder", "needs reorder"],
    "zero_stock": ["zero stock", "no stock", "out of stock", "stockout", "stock out"],
    "seasonal": ["seasonal", "season"],
    "basic": ["basic", "stable"],
    "regular": ["regular"],
    "new": ["new", "recent"],
    "bestseller": ["bestseller", "bestsellers", "best seller", "best sellers", "top selling"],
    "overstock": ["overstock", "overstocked", "excess", "surplus"],
}

TIME_KEYWORDS = {
    "last": ["last", "past", "previous", "recent"],
    "this": ["this", "current"],
    "next": ["next", "upcoming", "future"],
}


def translate_to_english(text: str) -> str:
    words = text.lower().split()
    translated = []
    for word in words:
        clean_word = word.strip(".,;:!?()[]{}\"'")
        if clean_word in PL_TO_EN:
            translated.append(PL_TO_EN[clean_word])
        else:
            translated.append(clean_word)
    return " ".join(translated)
